#!/bin/bash

if [ "$(javac --version | awk '{print $2}')" -lt "14" ]; then
        echo "Please update Java to version 14 or newer"
        exit
fi

printf "\nCompiling source code\n"
find src/ -name '*.java' | xargs javac -d bin
printf "\nGame starting\n\n"
java -Dfile.encoding=UTF-8 -cp "bin/" edu.bu.phuminw.quest.Quest